In [1]:
import pandas as pd

df = pd.read_csv("../data/Womens Clothing E-Commerce Reviews.csv")

print(df.shape)

(23486, 11)

In [2]:
low_rated = df[df["Rating"] <= 3].copy()

print("Total low-rated reviews:", len(low_rated))

Total low-rated reviews: 5278

In [3]:
sample_200 = low_rated.sample(n=200, random_state=42).copy()

print("Sample size:", len(sample_200))
sample_200.head()

Sample size: 200

,Unnamed: 0,Clothing ID,Age,Title,Review Text,Rating,Recommended IND,Positive Feedback Count,Division Name,Department Name,Class Name
26,26,949,33,Huge disappointment,I have been waiting for this sweater coat to s...,2,0,0,General,Tops,Sweaters
18807,18807,1094,46,Abroad dress,This is a heavy dress - it's surprising when y...,3,0,2,General Petite,Dresses,Dresses
2334,2334,1047,37,Ripped on first day,Perfect summer pants until i wanted to pet my ...,3,0,1,General Petite,Bottoms,Pants
8059,8059,1078,46,Wrinkled!,The dress arrived wrinkled so i washed it and ...,1,0,0,General Petite,Dresses,Dresses
17498,17498,1081,24,"Almost perfect, but the top is unflattering.","The dress had great potential, but the top sag...",3,0,0,General Petite,Dresses,Dresses

In [4]:
print("Missing review text:", sample_200["Review Text"].isna().sum())
print("Rating distribution:")
print(sample_200["Rating"].value_counts().sort_index())

Missing review text: 7
Rating distribution:
Rating
1     27
2     55
3    118
Name: count, dtype: int64

In [5]:
sample_200["Review Text"] = sample_200["Review Text"].fillna("")

llm_reviews = sample_200[sample_200["Review Text"].str.strip() != ""].copy()

print("Reviews with text for LLM:", len(llm_reviews))
print("Reviews excluded due to missing text:", len(sample_200) - len(llm_reviews))

Reviews with text for LLM: 193
Reviews excluded due to missing text: 7

In [6]:
labels = [
    "size/fit",
    "fabric/quality",
    "looks different from photo",
    "comfort",
    "price",
    "other"
]

prompt_template = """
You are classifying customer reviews for a women's clothing retailer.

Choose exactly ONE main issue from these labels:
1. size/fit
2. fabric/quality
3. looks different from photo
4. comfort
5. price
6. other

Also identify whether the review says the item runs:
- small
- large
- neither

Return ONLY this format:
issue|fit

Do not add explanations.

Review:
{review}
"""

print("Labels:", labels)
print(prompt_template)

Labels: ['size/fit', 'fabric/quality', 'looks different from photo', 'comfort', 'price', 'other']

You are classifying customer reviews for a women's clothing retailer.

Choose exactly ONE main issue from these labels:
1. size/fit
2. fabric/quality
3. looks different from photo
4. comfort
5. price
6. other

Also identify whether the review says the item runs:
- small
- large
- neither

Return ONLY this format:
issue|fit

Do not add explanations.

Review:
{review}

In [7]:
from groq import Groq
from dotenv import load_dotenv
import os

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

print("Groq client connected successfully!")

Groq client connected successfully!

In [9]:
test_review = llm_reviews.iloc[0]["Review Text"]

test_prompt = prompt_template.format(review=test_review)

response = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "user",
            "content": test_prompt
        }
    ],
    temperature=0
)

print("Review:")
print(test_review)

print("\nLLM Output:")
print(response.choices[0].message.content)

Review:
I have been waiting for this sweater coat to ship for weeks and i was so excited for it to arrive. this coat is not true to size and made me look short and squat. the sleeves are very wide (although long). as a light weight fall coat the sleeves don't need to be as wide because you wouldn't be layerng too much underneath. the buttons need to be moved at least three inches in for a nicer fit. i thought about redoing the buttons myself but the sleeves looked even more out of proportion with a tigh

LLM Output:
size/fit|small

In [10]:
llm_output = response.choices[0].message.content.strip()

parts = llm_output.split("|")

print("Raw output:", llm_output)
print("Number of parts:", len(parts))

if len(parts) == 2:
    print("Issue:", parts[0].strip())
    print("Fit:", parts[1].strip())

Raw output: size/fit|small
Number of parts: 2
Issue: size/fit
Fit: small

In [11]:
import time

results = []

for _, row in llm_reviews.iterrows():
    review = row["Review Text"]
    prompt = prompt_template.format(review=review)

    try:
        response = client.chat.completions.create(
            model="openai/gpt-oss-20b",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0
        )

        raw_output = response.choices[0].message.content.strip()

        parts = raw_output.split("|")

        if len(parts) == 2:
            issue = parts[0].strip()
            fit = parts[1].strip()
        else:
            issue = "parse_error"
            fit = "parse_error"

    except Exception as e:
        raw_output = str(e)
        issue = "error"
        fit = "error"

    results.append({
        "Review ID": row["Unnamed: 0"],
        "Clothing ID": row["Clothing ID"],
        "Department Name": row["Department Name"],
        "Rating": row["Rating"],
        "Review Text": review,
        "Issue": issue,
        "Fit": fit,
        "Raw Output": raw_output
    })

    time.sleep(0.1)

llm_results = pd.DataFrame(results)

print("Reviews processed:", len(llm_results))
print("\nIssue counts:")
print(llm_results["Issue"].value_counts())

print("\nFit counts:")
print(llm_results["Fit"].value_counts())

Reviews processed: 193

Issue counts:
Issue
size/fit                      137
fabric/quality                 29
looks different from photo     12
other                           7
parse_error                     3
price                           2
comfort                         2
2                               1
Name: count, dtype: int64

Fit counts:
Fit
neither        72
large          64
small          54
parse_error     3
Name: count, dtype: int64

In [12]:
invalid_results = llm_results[
    ~llm_results["Issue"].isin(labels)
]

print(invalid_results[
    ["Review ID", "Review Text", "Issue", "Fit", "Raw Output"]
].to_string(index=False))

 Review ID                                                                                                                                                                                                                                                                                                                                                                                                                Review Text       Issue         Fit                                                            Raw Output
     19115                                                                                                            Love the way this dress looks online. sadly, it doesn't look great on me. i'm 5'4", athletic build. the small fit perfectly, but the extra fabric in the hip/pocket area just seemed to drag me down. i really wished this worked for me, but i think you've gotta be a little bit taller to pull this one off. parse_error parse_error
     22126                                                                                                                                                                                                                                                                                                                                                                                                Super itchy! had to return.           2     neither                                                             2|neither
     22824 1. i'm 5'6" tall with a short waist and long legs, and this skirt came all the way down to my ankles. i would have kept it if it had stopped mid-calf like in the photo.\n\n2. i'm 38-32-40 and the size 12 fit me perfectly in the waist hip area, so i would say it runs true to size.\n\n3. the buttons lay nice and flat over the tummy, so that's a plus. at least you don't have to undo them to go to the bathroom. parse_error parse_error looks different from photo|neither\nsize/fit|neither\ncomfort|neither
     10197                                                                                                                                                                                                                                                                                                                                                                        Large and the material is too bulky. i returned it. parse_error parse_error

In [13]:
invalid_indices = llm_results[
    ~llm_results["Issue"].isin(labels)
].index

for idx in invalid_indices:
    review = llm_results.loc[idx, "Review Text"]
    prompt = prompt_template.format(review=review)

    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    raw_output = response.choices[0].message.content.strip()

    print("=" * 80)
    print("Review ID:", llm_results.loc[idx, "Review ID"])
    print("New LLM Output:", raw_output)

================================================================================
Review ID: 19115
New LLM Output: size/fit|neither
================================================================================
Review ID: 22126
New LLM Output: 2|neither
================================================================================
Review ID: 22824
New LLM Output: looks different from photo|neither
size/fit|neither
comfort|neither
================================================================================
Review ID: 10197
New LLM Output:

In [14]:
print(
    llm_results.loc[
        llm_results["Review ID"] == 10197,
        ["Review ID", "Review Text", "Raw Output"]
    ].to_string(index=False)
)

 Review ID                                         Review Text Raw Output
     10197 Large and the material is too bulky. i returned it.

In [15]:
manual_30 = llm_results.sample(n=30, random_state=123).copy()

manual_30[
    ["Review ID", "Rating", "Department Name", "Review Text", "Issue", "Fit"]
]

,Review ID,Rating,Department Name,Review Text,Issue,Fit
72,16442,3,Bottoms,Super cute skirt. i decided to return it becau...,other,neither
4,17498,3,Dresses,"The dress had great potential, but the top sag...",size/fit,neither
79,1077,3,Tops,This top was quite voluminous when i purchased...,size/fit,small
171,3695,3,Tops,Unfortunately this piece has a very boxy cut a...,size/fit,neither
112,11415,3,Bottoms,"Nice soft jeans, cute style, and i wish i coul...",size/fit,small
71,11876,1,Bottoms,I tried on this jumpsuit in black and it was a...,size/fit,small
90,17204,2,Dresses,I bought a petite medium and the length was ri...,size/fit,large
93,5683,3,Dresses,I was excited to receive this dress because it...,size/fit,small
182,1196,3,Dresses,"I am 5'-7"" and 135 lbs, i bought a medium peti...",size/fit,large
147,609,3,Dresses,"I just tried on this dress in the store, in re...",size/fit,neither
41,16227,3,Bottoms,These are my first paige cords/pants and they ...,size/fit,small
144,4469,3,Tops,I was looking forward to this cute top to get ...,size/fit,small
85,1273,2,Tops,Didn't work on this curvy gal.\r\nsizing up wo...,size/fit,small
62,13572,3,Dresses,I really liked this dress in so many ways. i'm...,size/fit,neither
143,12900,3,Tops,I loved the color and the neckline was flatter...,size/fit,large
155,19850,3,Bottoms,First off: kudos to the other reviewers for se...,looks different from photo,neither
19,7215,3,Dresses,This just did not sit well on me. while the le...,size/fit,neither
107,9338,2,Tops,Purchased this in two colors online. purchased...,size/fit,large
163,21305,3,Dresses,Lovely style. i got the navy color and it's be...,fabric/quality,large
152,19248,3,Bottoms,I love the look and feel of these shorts - typ...,size/fit,large
176,22824,2,Bottoms,"1. i'm 5'6"" tall with a short waist and long l...",parse_error,parse_error
42,7847,3,Bottoms,I was so excited to get this! the fabric is be...,size/fit,small
26,5564,3,Dresses,"Just a warning, the yoke on this dress has seq...",looks different from photo,neither
173,22576,1,Bottoms,I bought an xl and they looked like they would...,size/fit,small
156,3557,3,Bottoms,Beautiful thick sturdy denim. probably the bes...,size/fit,small
95,7184,2,Dresses,I would have kept this dress if it weren't for...,size/fit,large
77,20477,3,Tops,"Okay, so this top has its redeeming qualities,...",other,neither
167,2554,3,Tops,This is so bulky and itchy...could not stand t...,size/fit,large
31,4033,3,Dresses,I thought i'd like this dress in the neutral c...,size/fit,neither
128,12894,3,Tops,This shirt has beautiful coloring but the mate...,fabric/quality,neither

In [16]:
manual_check = manual_30[
    ["Review ID", "Rating", "Department Name", "Review Text", "Issue", "Fit"]
].copy()

manual_check["Manual_Issue"] = ""
manual_check["Manual_Fit"] = ""

manual_check

,Review ID,Rating,Department Name,Review Text,Issue,Fit,Manual_Issue,Manual_Fit
72,16442,3,Bottoms,Super cute skirt. i decided to return it becau...,other,neither,,
4,17498,3,Dresses,"The dress had great potential, but the top sag...",size/fit,neither,,
79,1077,3,Tops,This top was quite voluminous when i purchased...,size/fit,small,,
171,3695,3,Tops,Unfortunately this piece has a very boxy cut a...,size/fit,neither,,
112,11415,3,Bottoms,"Nice soft jeans, cute style, and i wish i coul...",size/fit,small,,
71,11876,1,Bottoms,I tried on this jumpsuit in black and it was a...,size/fit,small,,
90,17204,2,Dresses,I bought a petite medium and the length was ri...,size/fit,large,,
93,5683,3,Dresses,I was excited to receive this dress because it...,size/fit,small,,
182,1196,3,Dresses,"I am 5'-7"" and 135 lbs, i bought a medium peti...",size/fit,large,,
147,609,3,Dresses,"I just tried on this dress in the store, in re...",size/fit,neither,,
41,16227,3,Bottoms,These are my first paige cords/pants and they ...,size/fit,small,,
144,4469,3,Tops,I was looking forward to this cute top to get ...,size/fit,small,,
85,1273,2,Tops,Didn't work on this curvy gal.\r\nsizing up wo...,size/fit,small,,
62,13572,3,Dresses,I really liked this dress in so many ways. i'm...,size/fit,neither,,
143,12900,3,Tops,I loved the color and the neckline was flatter...,size/fit,large,,
155,19850,3,Bottoms,First off: kudos to the other reviewers for se...,looks different from photo,neither,,
19,7215,3,Dresses,This just did not sit well on me. while the le...,size/fit,neither,,
107,9338,2,Tops,Purchased this in two colors online. purchased...,size/fit,large,,
163,21305,3,Dresses,Lovely style. i got the navy color and it's be...,fabric/quality,large,,
152,19248,3,Bottoms,I love the look and feel of these shorts - typ...,size/fit,large,,
176,22824,2,Bottoms,"1. i'm 5'6"" tall with a short waist and long l...",parse_error,parse_error,,
42,7847,3,Bottoms,I was so excited to get this! the fabric is be...,size/fit,small,,
26,5564,3,Dresses,"Just a warning, the yoke on this dress has seq...",looks different from photo,neither,,
173,22576,1,Bottoms,I bought an xl and they looked like they would...,size/fit,small,,
156,3557,3,Bottoms,Beautiful thick sturdy denim. probably the bes...,size/fit,small,,
95,7184,2,Dresses,I would have kept this dress if it weren't for...,size/fit,large,,
77,20477,3,Tops,"Okay, so this top has its redeeming qualities,...",other,neither,,
167,2554,3,Tops,This is so bulky and itchy...could not stand t...,size/fit,large,,
31,4033,3,Dresses,I thought i'd like this dress in the neutral c...,size/fit,neither,,
128,12894,3,Tops,This shirt has beautiful coloring but the mate...,fabric/quality,neither,,

In [17]:
row = manual_check.iloc[0]

print("Review ID:", row["Review ID"])
print("Rating:", row["Rating"])
print("Department:", row["Department Name"])

print("\nREVIEW:")
print(row["Review Text"])

print("\nLLM prediction:")
print("Issue:", row["Issue"])
print("Fit:", row["Fit"])

Review ID: 16442
Rating: 3
Department: Bottoms

REVIEW:
Super cute skirt. i decided to return it because i felt like i did't have enough tops to go with it.

LLM prediction:
Issue: other
Fit: neither

In [18]:
row = manual_check.iloc[1]

print("Review ID:", row["Review ID"])
print("Rating:", row["Rating"])
print("Department:", row["Department Name"])

print("\nREVIEW:")
print(row["Review Text"])

print("\nLLM prediction:")
print("Issue:", row["Issue"])
print("Fit:", row["Fit"])

Review ID: 17498
Rating: 3
Department: Dresses

REVIEW:
The dress had great potential, but the top sagged and made the dress look unflattering on me. unfortunately, i had to return it. the length was great, and the back and sides of the dress were nicely tailored and flattering. perhaps this would fit someone else better - i have a 34b/34c bust, and it didn't work for me.

LLM prediction:
Issue: size/fit
Fit: neither

In [19]:
for i, (_, row) in enumerate(manual_check.iterrows(), start=1):
    print("=" * 100)
    print(f"REVIEW {i}/30")
    print("Review ID:", row["Review ID"])
    print("Rating:", row["Rating"])
    print("Department:", row["Department Name"])
    print("\nREVIEW:")
    print(row["Review Text"])
    print("\nLLM prediction:")
    print("Issue:", row["Issue"])
    print("Fit:", row["Fit"])
    print()

====================================================================================================
REVIEW 1/30
Review ID: 16442
Rating: 3
Department: Bottoms

REVIEW:
Super cute skirt. i decided to return it because i felt like i did't have enough tops to go with it.

LLM prediction:
Issue: other
Fit: neither

====================================================================================================
REVIEW 2/30
Review ID: 17498
Rating: 3
Department: Dresses

REVIEW:
The dress had great potential, but the top sagged and made the dress look unflattering on me. unfortunately, i had to return it. the length was great, and the back and sides of the dress were nicely tailored and flattering. perhaps this would fit someone else better - i have a 34b/34c bust, and it didn't work for me.

LLM prediction:
Issue: size/fit
Fit: neither

====================================================================================================
REVIEW 3/30
Review ID: 1077
Rating: 3
Department: Tops

REVIEW:
This top was quite voluminous when i purchased it and i sized down to an xs, however after hand washing it once in cold water it has shrunk significantly. it still fits, but something to be aware of.

LLM prediction:
Issue: size/fit
Fit: small

====================================================================================================
REVIEW 4/30
Review ID: 3695
Rating: 3
Department: Tops

REVIEW:
Unfortunately this piece has a very boxy cut and the white layer is stiff and billows out - i am tall and thin but this made me look pregnant - very unflattering. i considered trying a smaller size, but i did not like the material too much either so i just returned it.

LLM prediction:
Issue: size/fit
Fit: neither

====================================================================================================
REVIEW 5/30
Review ID: 11415
Rating: 3
Department: Bottoms

REVIEW:
Nice soft jeans, cute style, and i wish i could keep them...they just are too small on me. :/ not sure if i've gained weight (which i don't think i have because i had on a size 28 pair of pants today) but i ordered a size 29 in these jeans and they zipped but just too snug around the waist. i would honestly need a 30 or 31. looks like they are selling out quickly so i doubt i'll be able to get the size i need.
if you have a small waist i think they would be fine but they don't fit my body type

LLM prediction:
Issue: size/fit
Fit: small

====================================================================================================
REVIEW 6/30
Review ID: 11876
Rating: 1
Department: Bottoms

REVIEW:
I tried on this jumpsuit in black and it was absolutely beautiful. i liked that it looked sort of like a tuxedo, i wore it one time and received so many compliments. when i washed it, however, it shrunk almost 1 size! the pant legs were high water. i even tried washing and restretching it because i loved the jumpsuit but it wouldn't budge, i think because rayon is not stretchable material. to my disappointment, i returned it. i really wished it would have worked out.

LLM prediction:
Issue: size/fit
Fit: small

====================================================================================================
REVIEW 7/30
Review ID: 17204
Rating: 2
Department: Dresses

REVIEW:
I bought a petite medium and the length was right, but it fit like a potato sack. it was quite comfortable, and didn't look completely terrible from the front, but from the side, it was terribly unflattering. when i tried it on my boyfriend saw it and said it looked like i was wearing a nightie. i don't do form-fitting clothing, but this was the exact opposite and flared out every which way. it's got to go back.

LLM prediction:
Issue: size/fit
Fit: large

====================================================================================================
REVIEW 8/30
Review ID: 5683
Rating: 3
Department: Dresses

REVIEW:
I was excited to receive this dress because it seemed like a beautiful, breezy dress for summer. unfortunately i didn't find the fit to be very flattering. as two other reviewers mentioned there is too much fabric creating an odd bunching especially at the back waistline. i also found the dress to be a little tight across the bustline, upper arms and shoulders. the bunching can be improved by pulling the fabric of the dress forward in the front but this creates more of a plunging neckline than i

LLM prediction:
Issue: size/fit
Fit: small

====================================================================================================
REVIEW 9/30
Review ID: 1196
Rating: 3
Department: Dresses

REVIEW:
I am 5'-7" and 135 lbs, i bought a medium petite as i wanted the dress to hit at my knees, instead of midi. this dress is easily 2 sizes bigger than expected. the pattern was not flattering on my although i'm sure it would be for others. i was happy with the length...

LLM prediction:
Issue: size/fit
Fit: large

====================================================================================================
REVIEW 10/30
Review ID: 609
Rating: 3
Department: Dresses

REVIEW:
I just tried on this dress in the store, in red, and i loved the off the shoulder design. the color is just as pictured online (a light poppy red). the neckline began a few inches below my collarbone and was super flattering. however, the skirt portion of this dress flared awkwardly at the hips, causing my hips to look much wider than they really are (and also disturbing the otherwise clean lines of the dress). it seemed to me that there was too much fabric at the back portion of the skirt than

LLM prediction:
Issue: size/fit
Fit: neither

====================================================================================================
REVIEW 11/30
Review ID: 16227
Rating: 3
Department: Bottoms

REVIEW:
These are my first paige cords/pants and they seem to run much smaller than the other brands i wear. i'm normally a 32 in all other brands but with these the waist is pretty tight. i do love the length (i'm 5'9 and they are plenty long.) i also love the bell/flare. i'm not sure what makes this brand so much more expensive as the quality though nice seems comparable to cheaper brands.

LLM prediction:
Issue: size/fit
Fit: small

====================================================================================================
REVIEW 12/30
Review ID: 4469
Rating: 3
Department: Tops

REVIEW:
I was looking forward to this cute top to get me through the winter, but the combination of the very think fabric and boxy shape did not work on my 5'2", 130 lb, 34d figure. the one i received also had an open unfinished seam beneath the zipper. i imagine this would be a great top for someone taller.

LLM prediction:
Issue: size/fit
Fit: small

====================================================================================================
REVIEW 13/30
Review ID: 1273
Rating: 2
Department: Tops

REVIEW:
Didn't work on this curvy gal.
sizing up would have helped with the button gaps, but the flowy shape of the blouse would have looked too maternity on a larger size.
major pass.

LLM prediction:
Issue: size/fit
Fit: small

====================================================================================================
REVIEW 14/30
Review ID: 13572
Rating: 3
Department: Dresses

REVIEW:
I really liked this dress in so many ways. i'm tall and pear-shaped so the flowy shape is great for me. however, the deal-breaker was how the armholes were cut. it isn't that obvious in the photos, but they are cut in around the bust in the front in a way that was really weird looking on me, and it was too expensive to keep something that's unflattering. too bad, if they had just had a normal armhole it would have been a home run. lovely fabric and nice that it has pockets.

LLM prediction:
Issue: size/fit
Fit: neither

====================================================================================================
REVIEW 15/30
Review ID: 12900
Rating: 3
Department: Tops

REVIEW:
I loved the color and the neckline was flattering. however, it would have fit me better in a petite size bc i am 5'3" and a 32f. it fits slim so to fit in my bust it was too long. also didn't think the fabric was good quality for this price.

LLM prediction:
Issue: size/fit
Fit: large

====================================================================================================
REVIEW 16/30
Review ID: 19850
Rating: 3
Department: Bottoms

REVIEW:
First off: kudos to the other reviewers for setting the expectation re: the color on these! they are not a dark rinse at all - not even close. they're a light-to-medium hue with fading down the front of the thighs. with that in mind, i do like the color - especially for spring - but would have been very miffed had i ordered these and they arrived so starkly different from the online photo.
----------
i typically wear a 27-29, depending on the brand and waist rise. these were an online return t

LLM prediction:
Issue: looks different from photo
Fit: neither

====================================================================================================
REVIEW 17/30
Review ID: 7215
Rating: 3
Department: Dresses

REVIEW:
This just did not sit well on me. while the length was fine and the fabric was a nice thick weave with a flattering amount of stretch, the twist at the shoulder just looked odd. it did not sit flat at all, so it just looked like i had gotten dressed in the dark and had not managed to sort out my sleeves. given the spot-on quality, i would definitely look into other items from this brand, but back this dress went.

LLM prediction:
Issue: size/fit
Fit: neither

====================================================================================================
REVIEW 18/30
Review ID: 9338
Rating: 2
Department: Tops

REVIEW:
Purchased this in two colors online. purchased in an xs - i am usually a s or xs. the fit was really large in the xs and the seam on the front of the top was in the wrong place and was really unflattering. returning both.

LLM prediction:
Issue: size/fit
Fit: large

====================================================================================================
REVIEW 19/30
Review ID: 21305
Rating: 3
Department: Dresses

REVIEW:
Lovely style. i got the navy color and it's beautiful. i'm glad i ordered a smaller size after reading other reviews. my usual size would have been too big and not as figure flattering. but but but the sweater came pilled all over. i don't know if it had been worn and returned or if it's just the quality of the material but seriously there was pilling on the entire sweater. because the style is so nice and it fits well, i'm going to keep it and de-pill it but was disappointed with retailer :(

LLM prediction:
Issue: fabric/quality
Fit: large

====================================================================================================
REVIEW 20/30
Review ID: 19248
Rating: 3
Department: Bottoms

REVIEW:
I love the look and feel of these shorts - typically my issue with any sort of cotton or linen shorts these days is that they're practically made of nothing, but these are comfortable and made of decent fabric. however, they run very large. being 100 lbs and about 5', i typically buy size 0 or xs, but these looked a bit ridiculous on me, with how big they are. i tried shrinking them in the wash, since they're 100% cotton, and that helped some, along with getting rid of the creases from shipping

LLM prediction:
Issue: size/fit
Fit: large

====================================================================================================
REVIEW 21/30
Review ID: 22824
Rating: 2
Department: Bottoms

REVIEW:
1. i'm 5'6" tall with a short waist and long legs, and this skirt came all the way down to my ankles. i would have kept it if it had stopped mid-calf like in the photo.

2. i'm 38-32-40 and the size 12 fit me perfectly in the waist hip area, so i would say it runs true to size.

3. the buttons lay nice and flat over the tummy, so that's a plus. at least you don't have to undo them to go to the bathroom.

LLM prediction:
Issue: parse_error
Fit: parse_error

====================================================================================================
REVIEW 22/30
Review ID: 7847
Rating: 3
Department: Bottoms

REVIEW:
I was so excited to get this! the fabric is beautiful - comfy soft and a great wash/print of blue. it reminded me of the ocean. however, the fit was off. the waist was too high, the length too short, and the straps to long. i was very disappointed. i considered taking it to the tailor before returning. ultimately, i decided to return.

LLM prediction:
Issue: size/fit
Fit: small

====================================================================================================
REVIEW 23/30
Review ID: 5564
Rating: 3
Department: Dresses

REVIEW:
Just a warning, the yoke on this dress has sequins underneath. i'm not a sparkle kinda gal, so as soon as i saw that, the dress went right back in the package and will be going back to the store. i wish that had been described or more evident in the pictures, to me, it cheapens the whole dress, which would otherwise be adorable.

LLM prediction:
Issue: looks different from photo
Fit: neither

====================================================================================================
REVIEW 24/30
Review ID: 22576
Rating: 1
Department: Bottoms

REVIEW:
I bought an xl and they looked like they would have been a small. can't review anything else because i couldn't even get them on.... ridiculous

LLM prediction:
Issue: size/fit
Fit: small

====================================================================================================
REVIEW 25/30
Review ID: 3557
Rating: 3
Department: Bottoms

REVIEW:
Beautiful thick sturdy denim. probably the best denim i own in terms of the material. the cut can be awkward as it can be tight across the thighs and hips and kinda makes my butt flat. however i love the wash and quality of the material and at a sales price, totally worth it.

LLM prediction:
Issue: size/fit
Fit: small

====================================================================================================
REVIEW 26/30
Review ID: 7184
Rating: 2
Department: Dresses

REVIEW:
I would have kept this dress if it weren't for the giant arm holes and reveal my entire bra on both sides. other than that, it looks just like it does on the model and is a nice, substantial material.

LLM prediction:
Issue: size/fit
Fit: large

====================================================================================================
REVIEW 27/30
Review ID: 20477
Rating: 3
Department: Tops

REVIEW:
Okay, so this top has its redeeming qualities, i promise! which is why i gave it 3 stars when i really wanted to give it two. but it's just not worth 2 because i'm sure it works for some people and the quality is just impeccable. for people who purchase this, it will last forever. it's sturdy cotton, not thin like many retailer tee materials. the lace detail and texture is on point and the neckline is very nice. it's a great looking top. my issue though, wasn't with the bust as other reviewers hav

LLM prediction:
Issue: other
Fit: neither

====================================================================================================
REVIEW 28/30
Review ID: 2554
Rating: 3
Department: Tops

REVIEW:
This is so bulky and itchy...could not stand to have it on! i'm a 6/8 & ordered the small, but it was still gigantic.

LLM prediction:
Issue: size/fit
Fit: large

====================================================================================================
REVIEW 29/30
Review ID: 4033
Rating: 3
Department: Dresses

REVIEW:
I thought i'd like this dress in the neutral color. i had to return it it as it was quite unflattering. the skirt made my hips look big and the uneven shape didn't help. the top fit well, in my usual 4 petite, i think it would look nice on some people, as it's something different but i am not one of those it worked on.

LLM prediction:
Issue: size/fit
Fit: neither

====================================================================================================
REVIEW 30/30
Review ID: 12894
Rating: 3
Department: Tops

REVIEW:
This shirt has beautiful coloring but the material wasn't as soft as i thought it would be. i was hoping they would be the super soft material, maybe washing them would help, but i didn't want to chance it so i returned them.

LLM prediction:
Issue: fabric/quality
Fit: neither

In [20]:
pd.set_option("display.max_colwidth", None)

manual_check[
    ["Review ID", "Rating", "Department Name", "Review Text", "Issue", "Fit"]
].to_string(index=False)

' Review ID  Rating Department Name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Review Text                      Issue         Fit\n     16442       3         Bottoms                                                                                                                                                                                                                                                                                                                                                                                                                     Super cute skirt. i decided to return it because i felt like i did\'t have enough tops to go with it.                      other     neither\n     17498       3         Dresses                                                                                                                                                                                           The dress had great potential, but the top sagged and made the dress look unflattering on me. unfortunately, i had to return it. the length was great, and the back and sides of the dress were nicely tailored and flattering. perhaps this would fit someone else better - i have a 34b/34c bust, and it didn\'t work for me.                   size/fit     neither\n      1077       3            Tops                                                                                                                                                                                                                                                                                                                  This top was quite voluminous when i purchased it and i sized down to an xs, however after hand washing it once in cold water it has shrunk significantly. it still fits, but something to be aware of.                   size/fit       small\n      3695       3            Tops                                                                                                                                                                                                                                            Unfortunately this piece has a very boxy cut and the white layer is stiff and billows out - i am tall and thin but this made me look pregnant - very unflattering. i considered trying a smaller size, but i did not like the material too much either so i just returned it.                   size/fit     neither\n     11415       3         Bottoms   Nice soft jeans, cute style, and i wish i could keep them...they just are too small on me. :/ not sure if i\'ve gained weight (which i don\'t think i have because i had on a size 28 pair of pants today) but i ordered a size 29 in these jeans and they zipped but just too snug around the waist. i would honestly need a 30 or 31. looks like they are selling out quickly so i doubt i\'ll be able to get the size i need. \\r\\nif you have a small waist i think they would be fine but they don\'t fit my body type                   size/fit       small\n     11876       1         Bottoms                                  I tried on this jumpsuit in black and it was absolutely beautiful. i liked that it looked sort of like a tuxedo, i wore it one time and received so many compliments. when i washed it, however, it shrunk almost 1 size! the pant legs were high water. i even tried washing and restretching it because i loved the jumpsuit but it wouldn\'t budge, i think because rayon is not stretchable material. to my disappointment, i returned it. i really wished it would have worked out.                   size/fit       small\n     17204       2         Dresses                                                                                          I bought a petite medium and the length was right, but it fit like a potato sack. it was quite comfortable, and didn\'t look completely terrible from the front, but from the side, it was terribly unflattering. when i tried it on my boyfriend saw it and said it looked like i was wearing a nightie. i don\'t do form-fitting clothing, but this was the exact opposite and flared out every which way. it\'s got to go back.                   size/fit       large\n      5683       3         Dresses     I was excited to receive this dress because it seemed like a beautiful, breezy dress for summer. unfortunately i didn\'t find the fit to be very flattering. as two other reviewers mentioned there is too much fabric creating an odd bunching especially at the back waistline. i also found the dress to be a little tight across the bustline, upper arms and shoulders. the bunching can be improved by pulling the fabric of the dress forward in the front but this creates more of a plunging neckline than i                   size/fit       small\n      1196       3         Dresses                                                                                                                                                                                                                                             I am 5\'-7" and 135 lbs, i bought a medium petite as i wanted the dress to hit at my knees, instead of midi. this dress is easily 2 sizes bigger than expected. the pattern was not flattering on my although i\'m sure it would be for others. i was happy with the length...                   size/fit       large\n       609       3         Dresses      I just tried on this dress in the store, in red, and i loved the off the shoulder design. the color is just as pictured online (a light poppy red). the neckline began a few inches below my collarbone and was super flattering. however, the skirt portion of this dress flared awkwardly at the hips, causing my hips to look much wider than they really are (and also disturbing the otherwise clean lines of the dress). it seemed to me that there was too much fabric at the back portion of the skirt than                   size/fit     neither\n     16227       3         Bottoms                                                                                                                       These are my first paige cords/pants and they seem to run much smaller than the other brands i wear. i\'m normally a 32 in all other brands but with these the waist is pretty tight. i do love the length (i\'m 5\'9 and they are plenty long.) i also love the bell/flare. i\'m not sure what makes this brand so much more expensive as the quality though nice seems comparable to cheaper brands.                   size/fit       small\n      4469       3            Tops                                                                                                                                                                                                            I was looking forward to this cute top to get me through the winter, but the combination of the very think fabric and boxy shape did not work on my 5\'2", 130 lb, 34d figure. the one i received also had an open unfinished seam beneath the zipper. i imagine this would be a great top for someone taller.                   size/fit       small\n      1273       2            Tops                                                                                                                                                                                                                                                                                                                                   Didn\'t work on this curvy gal.\\r\\nsizing up would have helped with the button gaps, but the flowy shape of the blouse would have looked too maternity on a larger size.\\r\\nmajor pass.                   size/fit       small\n     13572       3         Dresses                           I really liked this dress in so many ways. i\'m tall and pear-shaped so the flowy shape is great for me. however, the deal-breaker was how the armholes were cut. it isn\'t that obvious in the photos, but they are cut in around the bust in the front in a way that was really weird looking on me, and it was too expensive to keep something that\'s unflattering. too bad, if they had just had a normal armhole it would have been a home run. lovely fabric and nice that it has pockets.                   size/fit     neither\n     12900       3            Tops                                                                                                                                                                                                                                                                        I loved the color and the neckline was flattering. however, it would have fit me better in a petite size bc i am 5\'3" and a 32f. it fits slim so to fit in my bust it was too long. also didn\'t think the fabric was good quality for this price.                   size/fit       large\n     19850       3         Bottoms First off: kudos to the other reviewers for setting the expectation re: the color on these! they are not a dark rinse at all - not even close. they\'re a light-to-medium hue with fading down the front of the thighs. with that in mind, i do like the color - especially for spring - but would have been very miffed had i ordered these and they arrived so starkly different from the online photo.\\r\\n----------\\r\\ni typically wear a 27-29, depending on the brand and waist rise. these were an online return t looks different from photo     neither\n      7215       3         Dresses                                                                                         This just did not sit well on me. while the length was fine and the fabric was a nice thick weave with a flattering amount of stretch, the twist at the shoulder just looked odd. it did not sit flat at all, so it just looked like i had gotten dressed in the dark and had not managed to sort out my sleeves. given the spot-on quality, i would definitely look into other items from this brand, but back this dress went.                   size/fit     neither\n      9338       2            Tops                                                                                                                                                                                                                                                                                            Purchased this in two colors online. purchased in an xs - i am usually a s or xs. the fit was really large in the xs and the seam on the front of the top was in the wrong place and was really unflattering. returning both.                   size/fit       large\n     21305       3         Dresses        Lovely style. i got the navy color and it\'s beautiful. i\'m glad i ordered a smaller size after reading other reviews. my usual size would have been too big and not as figure flattering. but but but the sweater came pilled all over. i don\'t know if it had been worn and returned or if it\'s just the quality of the material but seriously there was pilling on the entire sweater. because the style is so nice and it fits well, i\'m going to keep it and de-pill it but was disappointed with retailer :(             fabric/quality       large\n     19248       3         Bottoms      I love the look and feel of these shorts - typically my issue with any sort of cotton or linen shorts these days is that they\'re practically made of nothing, but these are comfortable and made of decent fabric. however, they run very large. being 100 lbs and about 5\', i typically buy size 0 or xs, but these looked a bit ridiculous on me, with how big they are. i tried shrinking them in the wash, since they\'re 100% cotton, and that helped some, along with getting rid of the creases from shipping                   size/fit       large\n     22824       2         Bottoms                                                                                               1. i\'m 5\'6" tall with a short waist and long legs, and this skirt came all the way down to my ankles. i would have kept it if it had stopped mid-calf like in the photo.\\n\\n2. i\'m 38-32-40 and the size 12 fit me perfectly in the waist hip area, so i would say it runs true to size.\\n\\n3. the buttons lay nice and flat over the tummy, so that\'s a plus. at least you don\'t have to undo them to go to the bathroom.                parse_error parse_error\n      7847       3         Bottoms                                                                                                                                                                         I was so excited to get this! the fabric is beautiful - comfy soft and a great wash/print of blue. it reminded me of the ocean. however, the fit was off. the waist was too high, the length too short, and the straps to long. i was very disappointed. i considered taking it to the tailor before returning. ultimately, i decided to return.                   size/fit       small\n      5564       3         Dresses                                                                                                                                                                               Just a warning, the yoke on this dress has sequins underneath. i\'m not a sparkle kinda gal, so as soon as i saw that, the dress went right back in the package and will be going back to the store. i wish that had been described or more evident in the pictures, to me, it cheapens the whole dress, which would otherwise be adorable. looks different from photo     neither\n     22576       1         Bottoms                                                                                                                                                                                                                                                                                                                                                                          I bought an xl and they looked like they would have been a small. can\'t review anything else because i couldn\'t even get them on.... ridiculous                   size/fit       small\n      3557       3         Bottoms                                                                                                                                                                                                                                     Beautiful thick sturdy denim. probably the best denim i own in terms of the material. the cut can be awkward as it can be tight across the thighs and hips and kinda makes my butt flat. however i love the wash and quality of the material and at a sales price, totally worth it.                   size/fit       small\n      7184       2         Dresses                                                                                                                                                                                                                                                                                                                 I would have kept this dress if it weren\'t for the giant arm holes and reveal my entire bra on both sides. other than that, it looks just like it does on the model and is a nice, substantial material.                   size/fit       large\n     20477       3            Tops   Okay, so this top has its redeeming qualities, i promise! which is why i gave it 3 stars when i really wanted to give it two. but it\'s just not worth 2 because i\'m sure it works for some people and the quality is just impeccable. for people who purchase this, it will last forever. it\'s sturdy cotton, not thin like many retailer tee materials. the lace detail and texture is on point and the neckline is very nice. it\'s a great looking top. my issue though, wasn\'t with the bust as other reviewers hav                      other     neither\n      2554       3            Tops                                                                                                                                                                                                                                                                                                                                                                                                    This is so bulky and itchy...could not stand to have it on! i\'m a 6/8 & ordered the small, but it was still gigantic.                   size/fit       large\n      4033       3         Dresses                                                                                                                                                                                         I thought i\'d like this dress in the neutral color. i had to return it it as it was quite unflattering. the skirt made my hips look big and the uneven shape didn\'t help. the top fit well, in my usual 4 petite, i think it would look nice on some people, as it\'s something different but i am not one of those it worked on.                   size/fit     neither\n     12894       3            Tops                                                                                                                                                                                                                                                                                        This shirt has beautiful coloring but the material wasn\'t as soft as i thought it would be. i was hoping they would be the super soft material, maybe washing them would help, but i didn\'t want to chance it so i returned them.             fabric/quality     neither'

In [21]:
manual_check[
    ["Review ID", "Rating", "Department Name", "Review Text", "Issue", "Fit"]
].to_csv("../outputs/manual_30_check.csv", index=False)

print("Saved: outputs/manual_30_check.csv")

Saved: outputs/manual_30_check.csv

In [22]:
df[df["Unnamed: 0"] == 20477][["Unnamed: 0", "Review Text"]]

,Unnamed: 0,Review Text
20477,20477,"Okay, so this top has its redeeming qualities, i promise! which is why i gave it 3 stars when i really wanted to give it two. but it's just not worth 2 because i'm sure it works for some people and the quality is just impeccable. for people who purchase this, it will last forever. it's sturdy cotton, not thin like many retailer tee materials. the lace detail and texture is on point and the neckline is very nice. it's a great looking top. my issue though, wasn't with the bust as other reviewers hav"

In [23]:
print(df.loc[df["Unnamed: 0"] == 20477, "Review Text"].iloc[0])

Okay, so this top has its redeeming qualities, i promise! which is why i gave it 3 stars when i really wanted to give it two. but it's just not worth 2 because i'm sure it works for some people and the quality is just impeccable. for people who purchase this, it will last forever. it's sturdy cotton, not thin like many retailer tee materials. the lace detail and texture is on point and the neckline is very nice. it's a great looking top. my issue though, wasn't with the bust as other reviewers hav

In [24]:
manual_labels = {
    16442: ("other", "neither"),
    17498: ("size/fit", "neither"),
    1077: ("fabric/quality", "small"),
    3695: ("size/fit", "neither"),
    11415: ("size/fit", "small"),
    11876: ("fabric/quality", "neither"),
    17204: ("size/fit", "large"),
    5683: ("size/fit", "small"),
    1196: ("size/fit", "large"),
    609: ("size/fit", "neither"),
    16227: ("size/fit", "small"),
    4469: ("fabric/quality", "neither"),
    1273: ("size/fit", "small"),
    13572: ("size/fit", "neither"),
    12900: ("size/fit", "large"),
    19850: ("looks different from photo", "neither"),
    7215: ("size/fit", "neither"),
    9338: ("size/fit", "large"),
    21305: ("fabric/quality", "large"),
    19248: ("size/fit", "large"),
    22824: ("looks different from photo", "neither"),
    7847: ("size/fit", "small"),
    5564: ("looks different from photo", "neither"),
    22576: ("size/fit", "small"),
    3557: ("size/fit", "small"),
    7184: ("size/fit", "neither"),
    20477: ("other", "neither"),
    2554: ("comfort", "large"),
    4033: ("size/fit", "neither"),
    12894: ("fabric/quality", "neither")
}

manual_check["Manual_Issue"] = manual_check["Review ID"].map(
    lambda x: manual_labels[x][0]
)

manual_check["Manual_Fit"] = manual_check["Review ID"].map(
    lambda x: manual_labels[x][1]
)

manual_check["Issue_Match"] = (
    manual_check["Issue"] == manual_check["Manual_Issue"]
)

manual_check["Fit_Match"] = (
    manual_check["Fit"] == manual_check["Manual_Fit"]
)

print("Issue accuracy:",
      manual_check["Issue_Match"].mean() * 100, "%")

print("Fit accuracy:",
      manual_check["Fit_Match"].mean() * 100, "%")

print("Overall exact-match accuracy:",
      (
          manual_check["Issue_Match"] &
          manual_check["Fit_Match"]
      ).mean() * 100, "%")

Issue accuracy: 83.33333333333334 %
Fit accuracy: 86.66666666666667 %
Overall exact-match accuracy: 80.0 %

In [25]:
issue_by_department = (
    llm_results
    .groupby(["Department Name", "Issue"])
    .size()
    .unstack(fill_value=0)
)

print(issue_by_department)

Issue            2  comfort  fabric/quality  looks different from photo  \
Department Name
Bottoms          0        0               4                           1
Dresses          0        0              10                           4
Intimate         1        0               0                           1
Jackets          0        0               2                           0
Tops             0        2              13                           6
Trend            0        0               0                           0

Issue            other  parse_error  price  size/fit
Department Name
Bottoms              1            1      0        21
Dresses              2            1      0        48
Intimate             1            0      0         9
Jackets              0            0      1         4
Tops                 3            1      0        54
Trend                0            0      1         1

In [26]:
llm_results["Final_Issue"] = llm_results["Issue"]

fixes = {
    19115: "size/fit",
    22126: "comfort",
    22824: "looks different from photo",
    10197: "fabric/quality"
}

for review_id, issue in fixes.items():
    llm_results.loc[
        llm_results["Review ID"] == review_id,
        "Final_Issue"
    ] = issue

issue_by_department = (
    llm_results
    .groupby(["Department Name", "Final_Issue"])
    .size()
    .unstack(fill_value=0)
)

print(issue_by_department)

Final_Issue      comfort  fabric/quality  looks different from photo  other  \
Department Name
Bottoms                0               4                           2      1
Dresses                0              10                           4      2
Intimate               1               0                           1      1
Jackets                0               2                           0      0
Tops                   2              14                           6      3
Trend                  0               0                           0      0

Final_Issue      price  size/fit
Department Name
Bottoms              0        21
Dresses              0        49
Intimate             0         9
Jackets              1         4
Tops                 0        54
Trend                1         1

In [27]:
llm_results.to_csv(
    "../outputs/llm_tagged_193_reviews.csv",
    index=False
)

manual_check.to_csv(
    "../outputs/manual_30_check.csv",
    index=False
)

print("Saved: outputs/llm_tagged_193_reviews.csv")
print("Saved: outputs/manual_30_check.csv")

Saved: outputs/llm_tagged_193_reviews.csv
Saved: outputs/manual_30_check.csv